// <auto-generated />
using DateMe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateMe.Migrations
{
    [DbContext(typeof(DatingApplicationContext))]
    [Migration("20250223232936_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("DateMe.Models.Application", b =>
                {
                    b.Property<int>("applicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("creeperStalkerStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("majorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("occupation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("applicationId");

                    b.HasIndex("majorID");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("DateMe.Models.Major", b =>
                {
                    b.Property<int>("MajorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MajorID");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            MajorID = 1,
                            MajorName = "Human Development"
                        },
                        new
                        {
                            MajorID = 2,
                            MajorName = "Computer Science"
                        },
                        new
                        {
                            MajorID = 3,
                            MajorName = "Information Systems"
                        },
                        new
                        {
                            MajorID = 4,
                            MajorName = "Elementary Education"
                        },
                        new
                        {
                            MajorID = 5,
                            MajorName = "Other"
                        });
                });

            modelBuilder.Entity("DateMe.Models.Application", b =>
                {
                    b.HasOne("DateMe.Models.Major", "major")
                        .WithMany()
                        .HasForeignKey("majorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("major");
                });
#pragma warning restore 612, 618
        }
    }
}
